name: Node.js CI

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Create .env file
              run: |
                  touch .env
                  echo API_USERNAME=${{ secrets.API_USERNAME }} >> .env
                  echo API_TOKEN=${{ secrets.API_TOKEN }} >> .env
            - name: Install & Build
              run: |
                  npm ci
                  npm run build
            - name: Linting
              run: npm run lint
            - name: Testing
              run: npm run test
